---
- hosts: dev
  become: true
  vars:
    workspace_dir: "{{ workspace_dir | default(ansible_env.WORKSPACE) }}"
    gradle_image: "gradle:8.2.1-jdk17-alpine"
    kubectl_image: "dtzar/helm-kubectl"

  tasks:
    # Initial setup tasks
    - name: Install python pip
      apt:
        name: python3-pip
        state: present
        update_cache: yes
    
    - name: Install docker-py module
      apt:
        name: python3-docker
        state: present
        update_cache: yes

    - name: Install java 21
      apt:
        name: openjdk-21-jre
        state: present
        update_cache: yes

    # Setup stage tasks
    - name: Pull Gradle Docker image
      docker_image:
        name: "{{ gradle_image }}"
        source: pull
        force_source: yes

    - name: Pull Kubectl Docker image
      docker_image:
        name: "{{ kubectl_image }}"
        source: pull
        force_source: yes

    # Unit Test stage tasks
    - name: Find workspace directory
      shell: ls -d */ | head -n 1
      register: workspace_dir_result

    - name: Set workspace directory fact
      set_fact:
        project_dir: "{{ workspace_dir }}/{{ workspace_dir_result.stdout_lines[0] | trim }}"

    - name: Make gradlew executable
      file:
        path: "{{ project_dir }}/gradlew"
        mode: '+x'

    - name: Run Gradle tests
      command: "./gradlew clean test --build-cache"
      args:
        chdir: "{{ project_dir }}"
      register: test_result
      ignore_errors: yes

    - name: Check test results
      fail:
        msg: "Gradle tests failed: {{ test_result.stderr }}"
      when: test_result.rc != 0
    