---
- hosts: dev
  become: true
  vars:
    workspace_dir: "{{ workspace_dir | default(ansible_env.WORKSPACE) }}"
    remote_workspace: "/opt/jenkins/workspace/auth-service"
    docker_registry: "{{ docker_registry }}"
    helm_repo: "{{ helm_repo }}"

  tasks:
    - name: Setup environment
      block:
        - name: Pull required Docker images
          docker_image:
            name: "{{ item }}"
            source: pull
          loop:
            - "gradle:8.2.1-jdk17-alpine"
            - "dtzar/helm-kubectl"

    - name: Create and sync workspace
      block:
        - name: Create remote workspace directory
          file:
            path: "{{ remote_workspace }}"
            state: directory
            mode: '0755'
            owner: ubuntu
            group: ubuntu

        - name: Synchronize workspace
          synchronize:
            src: "{{ workspace_dir }}/"
            dest: "{{ remote_workspace }}"
            rsync_opts:
              - "--exclude=.git"
          become: no

        - name: Set jenkins ownership
          file:
            path: "{{ remote_workspace }}"
            state: directory
            recurse: yes
            owner: jenkins
            group: jenkins

    - name: Run Unit Tests
      block:
        - name: Make gradlew executable
          file:
            path: "{{ remote_workspace }}/gradlew"
            mode: '0755'

        - name: Run Gradle tests
          shell: |
            sudo -u jenkins ./gradlew clean test --build-cache
          args:
            chdir: "{{ remote_workspace }}"
          register: test_result

        - name: Check test results
          fail:
            msg: "Pipeline aborted due to test build failure: {{ test_result.stderr }}"
          when: test_result.rc != 0

    - name: Set Image Info
      block:
        - name: Get application version
          shell: |
            sudo -u jenkins ./gradlew properties -q | grep 'version:' | grep -v 'kotlin.version:' | awk -F ':' '{print $2}'
          args:
            chdir: "{{ remote_workspace }}"
          register: version_result

        - name: Set version fact
          set_fact:
            app_version: "{{ version_result.stdout | trim }}"

        - name: Get chart name
          shell: |
            docker run -v {{ remote_workspace }}:/app -w /app dtzar/helm-kubectl helm show chart ./charts | grep name | cut -d: -f 2 | tr -d ' '
          register: chart_name_result

        - name: Set chart facts
          set_fact:
            chart_name: "{{ chart_name_result.stdout | trim }}"
            app_name: "{{ chart_name_result.stdout | trim }}-{{ env_type }}"

    - name: Build and Push Docker Image
      block:
        - name: Build Docker image
          shell: |
            docker build -t {{ docker_registry }}/{{ app_name }}:{{ app_version }} {{ remote_workspace }}
          register: docker_build

        - name: Login to Docker registry
          shell: |
            docker login {{ docker_registry }} -u {{ docker_user }} -p {{ docker_pass }}
          no_log: true
          when: docker_build.rc == 0

        - name: Push Docker images
          shell: |
            docker push {{ docker_registry }}/{{ app_name }}:{{ app_version }} && \
            docker tag {{ docker_registry }}/{{ app_name }}:{{ app_version }} {{ docker_registry }}/{{ app_name }}:latest && \
            docker push {{ docker_registry }}/{{ app_name }}:latest
          when: docker_build.rc == 0

    - name: Package and Push Helm Chart
      block:
        - name: Package Helm chart
          shell: |
            docker run --rm -v {{ remote_workspace }}:/app -w /app dtzar/helm-kubectl helm package charts/ --app-version {{ app_version }} --version {{ app_version }}
          args:
            chdir: "{{ remote_workspace }}"

        - name: Push Helm chart
          shell: |
            curl -u {{ docker_user }}:{{ docker_pass }} {{ helm_repo }} --upload-file {{ chart_name }}-{{ app_version }}.tgz -v
          args:
            chdir: "{{ remote_workspace }}"

    - name: Deploy Application
      block:
        - name: Deploy to Development
          shell: |
            ssh ubuntu@10.0.3.74 'cd /home/ubuntu/agencify-backend && git fetch && git checkout {{ env_type }} && git pull origin {{ env_type }} --rebase && sudo docker compose up -d'
          when: env_type == 'dev'

        - name: Deploy to Staging
          shell: |
            ssh ubuntu@10.0.3.85 'cd /home/ubuntu/agencify-backend && git fetch && git checkout {{ env_type }} && git pull origin {{ env_type }} --rebase && sudo docker compose -f staging-compose.yml up -d'
          when: env_type == 'staging'

        - name: Deploy to Production
          shell: |
            docker run --rm \
              -v {{ remote_workspace }}:/app \
              -w /app \
              dtzar/helm-kubectl \
              helm upgrade --install \
              --set image.repository='{{ docker_registry }}/{{ app_name }}' \
              --set image.tag='{{ app_version }}' \
              --set ingress.domain='{{ k8s_domain }}' \
              --set ingress.route='{{ k8s_route }}' \
              {{ app_name }} charts/ -n {{ env_type }}
          when: env_type == 'prod'
    