---
- hosts: dev
  become: true
  become_user: ubuntu
  vars:
    env_type: "{{ env_type }}"
    branch_name: "{{ branch_name | default('develop') }}"
    app_name: "{{ app_name }}"
    app_version: "{{ app_version }}"
    k8s_secret: "{{ k8s_secret | default('k8sonNewDevNS-Dev') }}"
    k8s_api: "{{ k8s_api | default('https://10.0.3.149:6443') }}"
    k8s_domain: "{{ k8s_domain | default('janzi.agencify.insure') }}"
    k8s_route: "{{ k8s_route | default('/api') }}"
    docker_registry: "{{ docker_registry }}"

  tasks:
    - name: Print deployment info
      debug:
        msg: |
          Starting deployment to {{ env_type }} environment:
          - Branch: {{ branch_name }}
          - Application: {{ app_name }}
          - Version: {{ app_version }}
          - Domain: {{ k8s_domain }}
          - Route: {{ k8s_route }}

    - name: Verify current user
      shell: whoami
      register: current_user
      

    # - name: Show current user
    #   debug:
    #     msg: "Current user is: {{ current_user.stdout }}"

    # - name: Deploy to dev environment
    #   when: env_type == 'dev'
    #   block:
    #     - name: Clone or update repository
    #       git:
    #         repo: https://github.com/fu-ry17/auth-service.git
    #         dest: /home/ubuntu/demo-backend
    #         version: "{{ branch_name }}"
    #         force: yes

    #     - name: Start docker compose
    #       shell: |
    #         cd /home/ubuntu/agencify-backend && \
    #         docker compose up -d
    #       register: deploy_result

    #     - name: Show deployment result
    #       debug:
    #         msg: |
    #           Deployment output:
    #           {{ deploy_result.stdout_lines | default([]) }}