---
- hosts: dev
  become: true
  become_user: ubuntu
  vars:
    env_type: "{{ env_type }}"
    branch_name: "{{ branch_name | default('develop') }}"
    app_name: "{{ app_name }}"
    app_version: "{{ app_version }}"
    k8s_secret: "{{ k8s_secret | default('k8sonNewDevNS-Dev') }}"
    k8s_api: "{{ k8s_api | default('https://10.0.3.149:6443') }}"
    k8s_domain: "{{ k8s_domain | default('janzi.agencify.insure') }}"
    k8s_route: "{{ k8s_route | default('/api') }}"
    docker_registry: "{{ docker_registry }}"

  tasks:
    - name: Print deployment info
      debug:
        msg: |
          Starting deployment to {{ env_type }} environment:
          - Branch: {{ branch_name }}
          - Application: {{ app_name }}
          - Version: {{ app_version }}
          - Domain: {{ k8s_domain }}
          - Route: {{ k8s_route }}

    - name: Verify current user
      shell: whoami
      register: current_user

    - name: Show current user
      debug:
        msg: "Current user is: {{ current_user.stdout }}"

    - name: Check if directory exists
      stat:
        path: /home/ubuntu/agencify-backend
      register: backend_dir

    - name: Show directory status
      debug:
        msg: "Backend directory {{ 'exists' if backend_dir.stat.exists else 'does not exist' }}"

    # - name: Deploy to dev environment
    #   when: env_type == 'dev'
    #   block:
    #     - name: Clone or update repository
    #       git:
    #         repo: https://github.com/fu-ry17/auth-service.git
    #         dest: /home/ubuntu/agencify-backend
    #         version: "{{ branch_name }}"
    #         force: yes
    #       register: git_result

    #     - name: Show git operation result
    #       debug:
    #         msg: |
    #           Git operation completed:
    #           Changed: {{ git_result.changed }}
    #           Before: {{ git_result.before }}
    #           After: {{ git_result.after }}

    #     - name: Check Docker status
    #       shell: docker ps
    #       register: docker_status
    #       ignore_errors: yes

    #     - name: Show Docker status
    #       debug:
    #         msg: |
    #           Docker containers:
    #           {{ docker_status.stdout_lines | default([]) }}

    #     - name: Start docker compose
    #       shell: |
    #         cd /home/ubuntu/agencify-backend && \
    #         echo "Current directory: $(pwd)" && \
    #         echo "Docker compose version: $(docker compose version)" && \
    #         echo "Starting containers..." && \
    #         docker compose up -d
    #       register: deploy_result

    #     - name: Show deployment result
    #       debug:
    #         msg: |
    #           Deployment output:
    #           {{ deploy_result.stdout_lines | default([]) }}
              
    #           Errors (if any):
    #           {{ deploy_result.stderr_lines | default([]) }}

    #     - name: Verify deployment
    #       shell: |
    #         echo "Checking running containers..."
    #         docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    #       register: verify_result

    #     - name: Show verification result
    #       debug:
    #         msg: |
    #           Running containers:
    #           {{ verify_result.stdout_lines | default([]) }}

    # - name: Show deployment errors
    #   debug:
    #     msg: |
    #       Deployment failed:
    #       {{ deploy_result.stderr_lines | default([]) }}
    #   when: deploy_result is failed
    #   failed_when: true

    # - name: Show deployment success
    #   debug:
    #     msg: |
    #       Deployment completed successfully:
    #       {{ deploy_result.stdout_lines | default([]) }}
    #   when: deploy_result is success