kind: Service
apiVersion: v1
metadata:
  name: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 60238
  type: NodePort

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  selector:
      matchLabels:
        app: auth-service
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: REGISTRY_LOCATION
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
          ports:
            - containerPort: 60238
          env:
            - name: JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: MYSQL_USERNAME
              valueFrom: # Read environment variables from kubernetes secrets
                secretKeyRef:
                  name: agencify-db
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: agencify-db
                  key: password
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: agencify-db
                  key: host
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                secretKeyRef:
                  name: agencify-envs
                  key: profile
          readinessProbe:
            initialDelaySeconds: 200
            periodSeconds: 5
            timeoutSeconds: 3
            successThreshold: 2
            failureThreshold: 4
            httpGet:
              path: /actuator
              port: 60238
          livenessProbe:
            httpGet:
              path: /actuator
              port: 60238
            initialDelaySeconds: 350
            timeoutSeconds: 3
            successThreshold: 1
            periodSeconds: 5
            failureThreshold: 4

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: auth-service

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
